### PR TITLE
Get the SwaggerSchemaFilter working

### PR DESCRIPTION
**Pull request by heldersepu**
Switch to Swagger-Net, I made the correction there.
Made some change to the Controller to improve a bit the readability

### CODE REVIEW

**Comment by OskarKlintrot** [comment]
Cool, thanks! Will the fix be added to Swashbuckle as well? That is what we are using at work. The change done in Swagger-Net didn't look to overwhelming.

**Comment by heldersepu** [comment]
Sorry, i gave up with swashbucle...
The releases are too slow

On Dec 1, 2017 2:18 AM, "Oskar Klintrot" <notifications@github.com> wrote:

Cool, thanks! Will the fix be added to Swashbuckle as well? That is what we
are using at work.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OskarKlintrot/swagger-issue-1197/pull/1#issuecomment-348420453>,
or mute the thread

**Comment by OskarKlintrot** [comment]
To bad but I do understand you. Can I open a PR to Swashbuckle with your fix? Hopefully it will be merged and released eventually...

**Comment by OskarKlintrot** [comment]
Or maybe not: https://github.com/domaindrivendev/Swashbuckle/pull/445

**Comment by heldersepu** [comment]
Sure you can.
But I will strongly recommend you to use Swagger-Net, I'm actively fixing bugs and adding new features, also I'm using the latest of the Swagger-UI and all other dependencies

**Comment by OskarKlintrot** [comment]
Not really my call to make but your project looks more active than Swashbuckle (it's 2 years since a PR with this fix was opened).

**Comment by heldersepu** [comment]
Exactly my point! see that PR 445, it was opened in Jul 2015...
If is not your call who is it, I will be happy to talk to them!

I've been trying to keep Swagger-Net as compatible with Swashbuckle as possible, the only major breaking change is the UI, as long as you guys don't have any UI customizations the migration should be just a few minutes.

**Comment by OskarKlintrot** [comment]
Yeah, that is painfully slow... But to be fair, the PR owner stopped responding to the reviewer.

Nice to hear! If we end up missing anything more in Swashbuckle I will definitely root for Swagger-Net!

**Comment by heldersepu** [comment]
I see your PR on Swashbuckle still open... 
How long has it been? 2..3 months? 

Since then I had more than 10 releases: 
https://www.nuget.org/packages/Swagger-Net

**Comment by OskarKlintrot** [comment]
I know, it's a joke...

**Pull request closed without merging**
